### ISSUE TITLE
No GUI and no results

### ISSUE THREAD

**Issue by mel-ctrl** [lukasvst/dm-vio-python-tools#1]
Hi,
I can not get dm-vio to work with the provided python tools. There are no build/execution errors, however, the program starts running (see figure) without showing a GUI and no results are recorded in the results folder.

![image](https://user-images.githubusercontent.com/68641403/161930914-cc4c4221-7c6f-4202-8f80-e1aff3c6d35b.png)

**Comment by lukasvst** [comment]
The command you run looks correct and should open the GUI.
Can you post the commandline output of DM-VIO? When running on the sequence it should print out some lines for each image tracked, like the estimated scale, etc.

You could also run the command with `output=save` and send me the results folder, then I can have a closer look. (Note that the subfolder setup contains some information about your system, so you might want to send it via E-Mail instead of publicly.)

**Comment by lukasvst** [comment]
Do you have any update on this, could the problem be resolved?
Otherwise I will close the issue in a couple of days.
